import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import Nav from "@/components/dashboard/nav";
import Footer from "@/components/dashboard/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 flex`}
    >
      <Nav />
      <div className="flex my-4 flex-col max-h-screen px-4 border-x-2 border-slate-100 lg:w-[1500px]  lg:max-w-[1500px] mx-auto">
        <div className="h-[100%]">{children}</div>
        <div>
          <Footer />
        </div>
      </div>
    </div>
  );
}
