import type { Metadata } from "next";
import "../globals.css";

import MegaMenu from "@/components/header/menu";

import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MegaMenu />
      <div className="min-h-screen ">{children}</div>
      <Footer />
    </>
  );
}
